### ISSUE TITLE
Different compression tables for specific file types?

### ISSUE THREAD

**Issue by winkmichael** [garysharp/SmazSharp#3]
Could this library be expanded to include different "key words" I.e. values specific to CSS, JSON or HTML? In many uses cases I find that when I try to compress JSON I end up with a much larger file. JSON has a few common things

{ "name":"John", "age":30, "car":null }

{" and ":"

**Comment by garysharp** [comment]
I made efforts to port [Shoco](https://github.com/Ed-von-Schleck/shoco) about 2 years ago. I managed to find the source which I never uploaded.

Also included is a port of the model generator - you pass it training data and it will generate a model which you can use live and/or export a `.cs` file to be included in your project. I would need to revisit the project before posting.

You can try out the Shoco library online using the [JavaScript port](http://ed-von-schleck.github.io/shoco/).

Would using a ported version of this project meet your requirements?

**Comment by winkmichael** [comment]
Hello Gary, that is really interesting! I did some tests with the Javascript port you reference and find that JSON data I am using compresses around 10% on average. In my case I basically send the JSON messages over the network, one message at a time. Example Message: { "SysID":"RockerMan", "Stat":"Online", "Load":"9.2" } This saving would be amazing! The idea of being able to further train it and gain more would be incredible! I suspect a great deal of users of users of modern bloat protocols like Json and XML would really benefit from that implantation. Generic compression protocols just don't help when doing short network messaging.

**Comment by garysharp** [comment]
I've published the Shoco port:
https://github.com/garysharp/ShocoSharp

I think the online Shoco library reports the amount of compression achieved, not the resulting size after the compression. The example you mentioned is compressed to 89% using the default model (11% compression achieved). You might achieve better results after training a model with your data.
